<div class="slider-row__brand">
    <div class="slider-brand__wrapper">
        <ul class="slider-brand owl-carousel" data-mage-init='{
    "OwlCarousel"         : {
    "items"               : 5,
    "loop"                : true,
    "margin"              : 2,
    "autoplay"            : true,
    "autoplayTimeout"     : 3000,
    "autoplayHoverPause"  : true
      }
    }'>
            <li class="slider-brand__logo">
                    <span class="image motorola">
                        <img src="<?= $block->escapeUrl($block->getViewFileUrl('Magento_Cms::images/brand/motorola_2.png')); ?>"
                             alt="brand motorola"
                        >
                    </span>
            </li>


            <li class="slider-brand__logo">
                    <span class="image baofeng">
                        <img src="<?= $block->escapeUrl($block->getViewFileUrl('Magento_Cms::images/brand/baofeng_2.png')); ?>"
                             alt="brand baofeng" width="240">
                    </span>
            </li>


            <li class="slider-brand__logo">
                    <span class="image icom">
                        <img src="<?= $block->escapeUrl($block->getViewFileUrl('Magento_Cms::images/brand/icom_2.png')); ?>"
                             alt="brand icom">
                    </span>
            </li>


            <li class="slider-brand__logo">
                    <span class="image kenwood">
                        <img src="<?= $block->escapeUrl($block->getViewFileUrl('Magento_Cms::images/brand/kenwood_2.png')); ?>"
                             alt="brand kenwood">
                    </span>
            </li>


            <li class="slider-brand__logo">
                    <span class="image hytera">
                        <img src="<?= $block->escapeUrl($block->getViewFileUrl('Magento_Cms::images/brand/hytera_2.png')); ?>"
                             alt="brand hytera">
                    </span>
            </li>

        </ul>

    </div>
</div>