<div class="modular-row callout modular-title-list">
    <div class="max-width">
        <h2 class="title">Bedankt voor uw bestelling bij PortofoonWEB!</h2>
        <div class="page-content">
            <div class="title-content">
                <div class="content-container">
                    <h3 class="content-title">Goed om te weten</h3>
                    <div class="content-text">
                        <p>Bent u tevreden over het bestelproces
                            like dan onze Facebook pagina of laat
                            een review achter, zo maakt u ook nog
                            eens kans op een leuke cadeau bon ter
                            waarde van € 100,- Wilt u graag op de
                            hoogte blijven van het laatste nieuws
                            en speciale aanbiedingen meld u zich
                            dan aan op onze nieuwsbrief.</p>
                    </div>
                </div>
            </div>
            <div class="title-content">
                <div class="content-container">
                    <h3 class="content-title">Wat gaat er nu gebeuren?</h3>
                    <div class="content-text">
                        <p>Per email heeft u een bevestiging ontvangen
                            van uw bestelling met Ordernummer [ordernummer].
                            Heeft u de bestelling op een werkdag voor 17:00
                            gedaan en betaald, dan gaan wij nu direct aan de
                            slag om te zorgen dat u het morgen in huis heeft.
                            Heeft u vragen over de bestelling neem dan contact
                            met ons op 0512 – 745293 of stuur ons een email aan
                            info@portofoonweb.nl. </p>
                    </div>
                </div>

            </div>
            <div class="title-content">
                <div class="content-container">
                    <h3 class="content-title">Wist u dat?</h3>
                    <div class="content-text">
                        <p>PortofoonWEB heeft sinds kort een fenomenaal
                            nieuwe techniek genaamd Smart Portofoons.
                            Een portofoon systeem met ongekende mogelijkheden
                            en onbeperkt bereik! Klik op deze link voor meer informatie. </p>
                    </div>
                </div>

            </div>
        </div>
        <div class="title-content_social">
            <div class="content-social_logo">
                    <span class="image logo-content">
                        <img src="<?= $block->escapeUrl($block->getViewFileUrl('Magento_Cms::images/title-page/Smartportofoon_Logo.png')); ?>"
                             alt="logo_title" width="200" height="50">
                    </span>
            </div>
            <div class="content-social_logo">
                <a href="http:\\facebook.com" class="image facebook">
                    <img src="<?= $block->escapeUrl($block->getViewFileUrl('Magento_Cms::images/title-page/facebook.svg')); ?>"
                         alt="logo_title">
                </a>
            </div>
            <div class="content-social_logo">
                <a href="http:\\twitter.com" class="image twitter">
                    <img src="<?= $block->escapeUrl($block->getViewFileUrl('Magento_Cms::images/title-page/twitter.svg')); ?>"
                         alt="logo_title">
                </a>
            </div>
        </div>

    </div>
</div>